networks:
  main:
    driver: bridge

services:
  database:
    image: bitnami/postgresql
    container_name: likedelivery_database
    volumes:
      - ./dbdata/postgresql:/bitnami/postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - main
